### ISSUE TITLE
eliot sometimes logs messages without `timestamp` or `task_uuid`.

### ISSUE THREAD

**Issue by tomprince** [jonathanj/eliottree#10]
- `eliot:destination_failure` doesn't have either (https://github.com/ClusterHQ/eliot/issues/165)
- Messages with out a top-level action don't have a `task_uuid`.

**Comment by jonathanj** [comment]
Hmm. @tomprince What would you suggest doing about missing `task_uuid`s?

**Comment by tomprince** [comment]
I'm not sure, which is why this is an issue, not an PR. :grinning:

**Comment by mithrandi** [comment]
If task_uuid is missing, just always render it as a top-level item, perhaps? (for example, you could generate a random task_uuid if one is not present, but there may be a more straightforward way)

**Comment by jonathanj** [comment]
Now that eliottree is using Eliot's builtin parser, parsing issues should be reported there. Incomplete trees will be listed after all the complete trees in the current implementation.
