### ISSUE TITLE
`--color=always` should always provide color

### ISSUE THREAD

**Issue by hacklschorsch** [jonathanj/eliottree#106]
Piping into a pager like `less` will make eliottree lose color:

    eliot-tree --color=always eliot.log  | less -R

`expect`'s `unbuffer` can help, as described in [this superuser.com post](https://superuser.com/a/1132741/417101):

    unbuffer eliot-tree --color=always eliot.log  | less -R

As per the linked post:

> Unfortunately some programs detect that their stdout is not a terminal and disable colors

Can eliottree please not disable colors when I ask it to?

**Comment by jonathanj** [comment]
I agree completely, in fact that's what `--color=always` was intended to do! Unfortunately it seems like a downstream dependency has its own TTY awareness that is interfering.
