### ISSUE TITLE
Prettier tree output

### ISSUE THREAD

**Issue by jml** [jonathanj/eliottree#19]
Over the weekend, I hacked together jml/tree-format, which renders Python trees in the format of the Unix `tree` command, e.g. 

```
foo
├── bar
│   ├── a
│   └── b
├── baz
└── qux
    └── c
```

Would you be interested in a patch that adds this mode of output to eliottree?

**Comment by jonathanj** [comment]
@jml these look great! Are these the Unicode or extended ASCII characters, are they supported on all terminal types? I'm happy to accept a change improving the tree characters provided that they are going to look right in all circumstances (or fall back to ASCII in cases where they need to.)

**Comment by jml** [comment]
They are unicode. They might also be extended ASCII. I basically just
copied from the output of `tree`. I guess I could poke around.

(Another option might be to just accept the patch and let users let us know
if they don't work?)

**Comment by mithrandi** [comment]
It would be nice to colourize the output too (eg. green for "succeeded" actions, red for failures).

**Comment by jonathanj** [comment]
@mithrandi Any idea how to do that? Can I do that and still use @jml's `tree-format` library?
