### ISSUE TITLE
Eliot-tree fails to parse log that does not have task_level of 1

### ISSUE THREAD

**Issue by myechuri** [jonathanj/eliottree#28]
In long running (> 1 hour) Flocker compute nodes, Eliot logs rotate, resulting in latest logs not having task_level of 1: https://clusterhq.atlassian.net/browse/FLOC-2943

```
vagrant@node1:/var/log/flocker$ eliot-tree flocker-dataset-agent.log
Traceback (most recent call last):
File "/usr/local/bin/eliot-tree", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/eliottree/_cli.py", line 94, in main
display_task_tree(args)
File "/usr/local/lib/python2.7/dist-packages/eliottree/_cli.py", line 47, in display_task_tree
nodes=tree.nodes(tree.merge_tasks(tasks, filter_funcs())),
File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 164, in merge_tasks
raise RuntimeError('Some tasks have no start parent', pending)
```
Would be useful to have eliot-tree help debug Flocker issues using production logs. Thanks a lot for any help fixing this issue!

**Comment by jonathanj** [comment]
@myechuri I noticed this issue in real-world Eliot logs myself a while after publishing the change. It seems like in real-world scenarios it is not uncommon for the start task to mysteriously not exist. I'm not sure why this would actually happen, perhaps neglecting to finish an action?

Anyway, eliottree should definitely be more resilient.

**Comment by jonathanj** [comment]
@myechuri I've created PR #29 for this, would you mind giving it a try to see if it resolves your problem?

**Comment by myechuri** [comment]
@jonathanj : thanks a lot for taking a look at the issue!

>  I'm not sure why this would actually happen, perhaps neglecting to finish an action?

It would happen if logs rotated and start task appeared in log-timestamp1 and end task appeared in log-timestamp2? Also, for long running tasks (main loop of a daemon, for example), we would never see the end task corresponding to the start of the loop?

>  I've created PR #29 for this, would you mind giving it a try to see if it resolves your problem?

Thank you! Will try it out and keep you posted by weekend.

**Comment by jonathanj** [comment]
Ah yes, log rotation is the obvious one, of course!

**Comment by myechuri** [comment]
With PR 29, ran eliot-tree on a set of log files from one Flocker process (flocker-dataset-agent):

1) First log file flocker-dataset-agent.log rendered fine:

```
vagrant@node1:/vagrant/app$ eliot-tree flocker-dataset-agent.log > flocker-dataset-agent.log.pretty
vagrant@node1:/vagrant/app$ head flocker-dataset-agent.log.pretty
6e0942af-78cc-4651-9484-87a34024c955
+-- <missing start task>@1/started
    `-- timestamp: 2015-08-26 21:40:23.527292
    +-- fsm:transition@2,2,2,2,2,2,2,2,1/started
        |-- fsm_identifier: <flocker.node._loop.ConvergenceLoop object at 0x7fbf7aa65310>
        |-- fsm_input: <ConvergenceLoopInputs=STATUS_UPDATE>
        |-- fsm_rich_input: <_ClientStatusUpdate>
        |-- fsm_state: <ConvergenceLoopStates=CONVERGING>
        `-- timestamp: 2015-08-26 21:40:23.527292
        +-- fsm:transition@2,2,2,2,2,2,2,2,2/succeeded
vagrant@node1:/vagrant/app$ 
```

2) Second log file flocker-dataset-agent.log.1 segfaulted:

```
vagrant@node1:/vagrant/app$ eliot-tree flocker-dataset-agent.log.1 
Segmentation fault
vagrant@node1:/vagrant/app$ 
```

3) Third log file flocker-dataset-agent.log.2 segfaulted as well:

```
vagrant@node1:/vagrant/app$ eliot-tree flocker-dataset-agent.log.2
Segmentation fault (core dumped)
vagrant@node1:/vagrant/app$
```

Looking into cause of segfault - will update shortly.

**Comment by myechuri** [comment]
Traceback for segfault:

```
vagrant@node1:/vagrant/app$ eliot-tree flocker-dataset-agent.log.1 
Fatal Python error: Segmentation fault

Current thread 0x00007feb64eab740 (most recent call first):
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 77 in _add_child
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 81 in _add_child
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 81 in _add_child
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 81 in _add_child
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 81 in _add_child
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 81 in _add_child
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 84 in add_child
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 175 in _merge
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 183 in merge_tasks
  File "/usr/local/lib/python2.7/dist-packages/eliottree/_cli.py", line 47 in display_task_tree
  File "/usr/local/lib/python2.7/dist-packages/eliottree/_cli.py", line 94 in main
  File "/usr/local/bin/eliot-tree", line 11 in <module>
Segmentation fault (core dumped)
```

Btw, can i please be granted access to contribute? Added ``faulthandler`` to get this traceback. Happy to check it in:

In ``tree.py``:
```python
import faulthandler
...
class Tree(object):
    """
    Eliot task tree.

    :ivar _nodes: Internal tree storage, use ``Tree.nodes`` or
        ``Tree.matching_nodes`` to obtain the tree nodes.
    """
    def __init__(self):
        self._nodes = {}
        faulthandler.enable()
```

**Comment by myechuri** [comment]
Segfault is coming from https://github.com/jonathanj/eliottree/blob/master/eliottree/tree.py#L77

```
levels = list(levels)
```

Wondering if levels are too deep for ``list``.

**Comment by myechuri** [comment]
A second run on the same log file (``flocker-dataset-agent.log.1``) threw segfault from a different location:

```
Current thread 0x00007f8d0df9d740 (most recent call first):
  File "/usr/lib/python2.7/collections.py", line 52 in __init__
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 51 in __init__
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 178 in _merge
  File "/usr/local/lib/python2.7/dist-packages/eliottree/tree.py", line 186 in merge_tasks
  File "/usr/local/lib/python2.7/dist-packages/eliottree/_cli.py", line 47 in display_task_tree
  File "/usr/local/lib/python2.7/dist-packages/eliottree/_cli.py", line 94 in main

```

``/usr/lib/python2.7/collections.py:52`` is 

```python
self.__update(*args, **kwds)
```
for ``class OrderedDict(dict):`` from https://github.com/jonathanj/eliottree/blob/28-resilient-missing-tasks/eliottree/tree.py#L173

**Comment by myechuri** [comment]
Uploaded Flocker logs (that ran into above segfaults) to https://drive.google.com/folderview?id=0ByymF9bLBknGcjFUQnkwYjVLeVk&usp=sharing

**Comment by jonathanj** [comment]
I am able to run `eliot-tree` on `flocker-dataset-agent.log.1` without issue:

```
$ eliot-tree flocker-dataset-agent.log.1 | wc -l
 1621814
```

It took quite a while to build the tree before displaying the output, intuition tells me this is more of a memory issue than anything. Building the tree for a 100MB Eliot log results in usage of at least 1GB for the tree structure and decoded JSON. Every line of the log has to be deserialized and held in memory before you can even start building the tree.

I don't think faulthandler has a place being in eliottree itself, you can easily run eliottree via faulthandler if you're trying to track down a bug, but considering it doesn't work on at least one major platform and is written in C and tied very closely to the CPython internals (sorry PyPy) I'm going to have to decline.

However, if you want to contribute a change feel free to submit a pull request and use the established Github workflow for contributing to a project.

**Comment by myechuri** [comment]
> It took quite a while to build the tree before displaying the output, intuition tells me this is more of a memory issue than anything.

As part of triaging, i increased stack size from default of 8MB to 16MB, did not notice a difference, hence, rejected the hypothesis.

> Building the tree for a 100MB Eliot log results in final usage of at least 1GB (expect more for the process of constructing the result) for the tree structure and decoded JSON. Every line of the log has to be deserialized and held in memory before you can even start building the tree.

Thanks for sharing! This is a huge limitation on post-processing Flocker production logs in-situ.

> I don't think faulthandler has a place being in eliottree itself, you can easily run eliottree via faulthandler if you're trying to track down a bug, but considering it doesn't work on at least one major platform and is written in C and tied very closely to the CPython internals (sorry PyPy) I'm going to have to decline.

Thanks for sharing the reason!

> However, if you want to contribute a change feel free to submit a pull request and use the established Github workflow for contributing to a project.

i attempted a push hoping to submit a PR, but push failed, hence reached out to you.

```
Madhuris-MacBook-Pro-2:eliottree madhuriyechuri$ git commit
[master 19bac76] Faulthandler tracebacks for SIGSEGV, SIGFPE, SIGABRT, SIGBUS, SIGKILL
 1 file changed, 2 insertions(+)
Madhuris-MacBook-Pro-2:eliottree madhuriyechuri$ git push
remote: Permission to jonathanj/eliottree.git denied to myechuri.
fatal: unable to access 'https://github.com/jonathanj/eliottree.git/': The requested URL returned error: 403
Madhuris-MacBook-Pro-2:eliottree madhuriyechuri$
```

Thanks!

**Comment by myechuri** [comment]
I am able to run eliot-tree on flocker-dataset-agent.log.1 without issue

@jonathanj : can you please share the stack size you used? Thanks a lot!

**Comment by jonathanj** [comment]
@myechuri I'm not sure how to get that information. Does this help?

```
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getrecursionlimit()
1000
```

**Comment by jonathanj** [comment]
@myechuri I think you'll find the information you need to know about creating PRs in the Github help: https://help.github.com/articles/using-pull-requests/

The brief—but important—highlights are: You fork the repo (so that you have a copy you have permission to write to), make the changes and submit a pull request to merge your changes back into the original.
