### ISSUE TITLE
Give me a way to select a time range of log messages

### ISSUE THREAD

**Issue by exarkun** [jonathanj/eliottree#38]
I have a big chunk of eliot logs.  I have another log file with timestamps in it like "2015-10-29 12:45:16+0000" that identify interesting time ranges.  I'd like to use eliot-tree (among other tools, perhaps) to examine the eliot logs specifically from those time ranges.

Something like:

```
eliot-tree --start "2015-10-29 12:45:16+0000" --end "..."
```

would be pretty great.

Something using the `--select` feature may well do the job too (though it's probably guaranteed to involve more typing - but shell aliases or something I guess :wink:).

I tried `--select "timestamp > ..."` but even with a ton of extra support code to convert date formats and such, eliot-tree (or jmespath, dunno) eventually gets angry at comparison between a datetime and an int.

**Comment by jonathanj** [comment]
Eliot tree transforms the tree while parsing it to support the human-readable features, `--raw` disables this, so  `--raw --select 'timestamp > ``...``'` should work.

Unfortunately this means that you don't get any human-readable output. I filed #39 to address this.

**Comment by jonathanj** [comment]
I'm going to reopen this because i think `--start ISO8601_timestamp` is a lot better than the corresponding `--select` incantation.
