### ISSUE TITLE
Render without graphics characters or display properly in less(1)

### ISSUE THREAD

**Issue by smontanaro** [jonathanj/eliottree#66]
Maybe his is a help request for less(1), and not a complaint about eliot-tree, but I think it might be handy if either:

- eliot-tree could be coaxed into rendering trees without VT100 graphics characters

or

- mention could be made in the README of how to get less(1) to properly render those characters.

**Comment by smontanaro** [comment]
Never mind. "less -r" does the trick.

**Comment by jonathanj** [comment]
Sorry about the delayed reply, @smontanaro! If `--color` is "auto" (the default) then `sys.stdout.isatty()` is consulted to determine whether color should be used. So you can either use `less -r` (or `less -R` which is often a better idea) or you can specify `--color=always` to eliot-tree to force it to output ANSI color codes.
