### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by RoyLarson** [jonathanj/eliottree#77]
According to the documents on eliot
https://eliot.readthedocs.io/en/stable/quickstart.html

this was on conda-forge at one time, would it be possible to put it back?

Thanks

**Comment by jonathanj** [comment]
@RoyLarson That looks like a documentation issue in Eliot, eliottree has never been available via conda-forge. I'm happy to accept a recipe for this though.

**Comment by RoyLarson** [comment]
I will see what I can do.  I have never built a recipe before, so that will be a first

**Comment by itamarst** [comment]
I've opened PR for the recipe; might take a few tweaks, but hopefully should have packages in a few days.

For future reference: Conda-Forge automation is really wonderful, creating new packages is quite easy (especially for simple pure-Python packages like this one).

**Comment by itamarst** [comment]
(And, sorry for the confusion in the docs @RoyLarson ).

**Comment by itamarst** [comment]
Alright, it's done: https://anaconda.org/conda-forge/eliot-tree

So you can close this issue, @jonathanj.
