### ISSUE TITLE
On my terminal, prints white-on-white text

### ISSUE THREAD

**Issue by njsmith** [jonathanj/eliottree#78]
On my terminal, eliot-tree output looks like:

![image](https://user-images.githubusercontent.com/609896/56775876-02154780-677e-11e9-98e7-bb233a2cbf1d.png)

I find that UUID somewhat hard to read :-)

**Comment by jonathanj** [comment]
Hi @njsmith! Do you have a suggestion to improve this?

From my point of view this looks like an issue with your terminal theme, if you have a light background then any light coloured text (from any application) is going to be illegible. If I change it to black, for example, then it’ll be illegible for someone with a dark theme background.

One’s terminal theme should be ensuring that doesn’t happen by making colour choices (foreground and background) that don’t hinder readability.

**Comment by njsmith** [comment]
I'm not sure I understand... are you saying that it's a bug to use a light background in terminals, or...?

I just double-checked and the same behavior happens with the default gnome-terminal theme, so presumably this affects more than just me :-).

I believe that some apps handle this by [checking the background color](https://stackoverflow.com/a/7767891/1925449), and picking between two sets of output colors depending on whether the background is closer to 0xffffff or 0x000000.

**Comment by jonathanj** [comment]
What I said was that if your terminal emulator is set up to render bright white on top of a light background that sounds very much like a configuration issue with your terminal emulator.

I tried `brew`, `htop` and `mtr` with a light background and neither of them made any accommodations for my poorly configured terminal emulator. My terminal emulator has a slider to adjust "Minimum contrast" to avoid this situation.

If you have a suggestion for how to improve the behaviour of eliot-tree, by detecting the background colour in compatible emulators, or by proposing a different colour for that item. I'm happy to consider them in the form of a PR.

**Comment by jtrakk** [comment]
Looks like this is fixed by the new themes and color detection.

**Comment by jonathanj** [comment]
@jtrakk Correct. Some rudimentary checking is done via the `COLORFGBG` environment variable (which some terminals seem to set) to guess whether the terminal is light or dark and switches themes accordingly. This behaviour can be overridden via the `--theme` option, and the colours can be changed entirely with [theme overrides](https://github.com/jonathanj/eliottree#theme-overrides).
