### ISSUE TITLE
Strange format

### ISSUE THREAD

**Issue by mozesa** [jonathanj/eliottree#80]
Dear **Jonathan**,

I would like to ask for your kind help.

This is the first time that I try to use `eliot` whit `eliot-tree`.

The problem that the result formatted by `eliot-tree` looks very both in `cmd, powershell` and `PyCharm's terminal`.

I use `Windows 10.`

![render](https://user-images.githubusercontent.com/49973426/70229753-15968100-1757-11ea-8f10-a7ac52cf69cf.png)

Thanks for your help in advance.

**Comment by jonathanj** [comment]
Hi @mozesa,

It looks like the shell isn't interpreting the colour codes, presumably these need to be different for cmd and powershell, bash in WSL should work but that might not be very useful to you.

I'm happy to accept a PR that adds colour support for Windows, I haven't looked into doing this myself yet so I have no additional advice.

For now you can disable colours by running eliot-tree with the `--color never` option.

**Comment by mozesa** [comment]
Thanks so much.

It solved the problem.
