### ISSUE TITLE
Command prompt & python usage

### ISSUE THREAD

**Issue by ghuname** [jonathanj/eliottree#81]
Hi,

I am using jupyter lab notebook to execute the following:

```
from eliot import log_call, to_file

eliot_file =r"c:\Users\user\Downloads\eliot.log"
to_file(open(eliot_file, "w"))

@log_call
def add(a, b):
    return a + b

@log_call
def multiply(a, b):
    return a * b

multiply(add(1,2), 4)
```

Result is 12, and content of eliot_file is:

```
{"a": 1, "b": 2, "action_status": "started", "timestamp": 1578133156.6194398, "task_uuid": "ecd3e4f3-3f20-428f-8392-2c719e60e674", "action_type": "__main__.add", "task_level": [1]}
{"result": 3, "action_status": "succeeded", "timestamp": 1578133156.6204777, "task_uuid": "ecd3e4f3-3f20-428f-8392-2c719e60e674", "action_type": "__main__.add", "task_level": [2]}
{"a": 3, "b": 4, "action_status": "started", "timestamp": 1578133156.6204777, "task_uuid": "fcd2c4d6-83c0-4133-b5c6-d9049ed960fb", "action_type": "__main__.multiply", "task_level": [1]}
{"result": 12, "action_status": "succeeded", "timestamp": 1578133156.6214757, "task_uuid": "fcd2c4d6-83c0-4133-b5c6-d9049ed960fb", "action_type": "__main__.multiply", "task_level": [2]}
```

From windows 10, command line "eliot-tree eliot.log", situation is as following:

![image](https://user-images.githubusercontent.com/15207713/71764349-17cf3500-2ee7-11ea-8d7f-ffa7939b91ba.png)

The picture above is with command prompt code page 437 (OEM - United States).
I tried to change code page to UTF-8 ("CHCP 65001"), but I still got special characters instead of symbols.

Question 1: How to set up windows 10 in order to get output of eliot-tree readable? 

I tried to get the tree directly from python3, but I am not sure how to create tasks in:

```
import json, sys
from eliottree import tasks_from_iterable, render_tasks
render_tasks(sys.stdout.write, tasks, colorize=True)
```

I tried:

```
with open(eliot_file, "r") as f:
    x = f.readlines()

```
and then

`render_tasks(sys.stdout.write, x, colorize=True)`

or 

```
y = tasks_from_iterable(x)
# or y = tasks_from_iterable(eliot_file)
render_tasks(sys.stdout.write, y, colorize=True)

```
but with no success ("<node formatting exception>").

Question 2: How to generate tasks from log file?

Regards.

**Comment by jonathanj** [comment]
Hi @ghuname,

Sorry to hear you've having trouble with eliot-tree.

To your first question:

What you're seeing are the VT100 escape codes for color being displayed literally in cmd, which is because cmd doesn't support VT100. This was reported before and there is a resolution in #80: Use `--color never`.

And to your second question:

`render_tasks` accepts an iterable of **parsed** Eliot logs, but `f.readlines` returns an array of **strings**. `tasks_from_iterable` accepts an iterable of `dict`, as described in the [function docstring](https://github.com/jonathanj/eliottree/blob/54e6c71d62c3ebe58aae6465f291a46b59e76ed8/src/eliottree/_parse.py#L12-L13), which means you will need to parse the lines as JSON before calling `tasks_from_iterable`.

So presumably you can change your code to do something like this:

```python
json_lines = [json.loads(line) for line in f]
tasks = tasks_from_iterable(json_lines)
render_tasks(sys.stdout.write, tasks)
```

The README could definitely have explained this better, I'll try find the time to make a PR to improve this.

**Comment by ghuname** [comment]
Hi,
> What you're seeing are the VT100 escape codes for color being displayed literally in cmd, which is because cmd doesn't support VT100. This was reported before and there is a resolution in #80: Use `--color never`.

--color never, helped partially as you can see at the picture bellow:

![image](https://user-images.githubusercontent.com/15207713/71781971-08c6b080-2fd5-11ea-9a04-42af13efdbfc.png)

How to get rid of question mark sign?

> So presumably you can change your code to do something like this:
> 
> ```python
> json_lines = [json.loads(line) for line in f]
> tasks = tasks_from_iterable(json_lines)
> render_tasks(sys.stdout.write, tasks)
> ```

This is workable solution:

```
with open(eliot_file, "r") as f:
    eliot_file_lines_array = f.readlines()

json_lines = [json.loads(line) for line in eliot_file_lines_array]
tasks = tasks_from_iterable(json_lines)
render_tasks(sys.stdout.write, tasks)
```
 
that produced:


```
ecd3e4f3-3f20-428f-8392-2c719e60e674
└── __main__.add/1 ⇒ started 1578133156.6194398 ⧖ 0.0010378360748291016
    ├── a: 1
    ├── b: 2
    └── __main__.add/2 ⇒ succeeded 1578133156.6204777
        └── result: 3

fcd2c4d6-83c0-4133-b5c6-d9049ed960fb
└── __main__.multiply/1 ⇒ started 1578133156.6204777 ⧖ 0.0009980201721191406
    ├── a: 3
    ├── b: 4
    └── __main__.multiply/2 ⇒ succeeded 1578133156.6214757
        └── result: 12
```

> The README could definitely have explained this better, I'll try find the time to make a PR to improve this.

This would definitively help some future user.

Thank you very much for helping me.
Best regards.

**Comment by ghuname** [comment]
I have another question about usage.
1. Is there a way to turn off eliot logging?
2. Is there a log rotate option?

Regards.

**Comment by jonathanj** [comment]
> How to get rid of question mark sign?

It is probably a missing glyph in the font you're using for your console, so changing your console font is one option, or just living with it is another option.

> 1. Is there a way to turn off eliot logging?
> 2. Is there a log rotate option?

These questions should be directed at [Eliot](https://github.com/itamarst/eliot) itself, not eliottree.
